name: 'Create Release With Tag'
description: 'Action for Create release with tag'
branding:
  icon: 'arrow-up-circle'
  color: 'black'
inputs:
  branch:
    description: 'Branch for release in repository'
    required: false
    default: ${{github.event.repository.default_branch}}
  tag:
    description: 'Tag name for release'
    required: true
  just-tag:
    description: 'Just set tag'
    required: false
    default: false
  gh-token:
    description: 'Token with credentials for repository'
    required: true
    default: ${{ github.token }}
  append-tag:
    description: 'Tag name for append in commit'
    required: false
  upper:
    description: 'Set append-tag name to uppercase'
    required: false
    default: false

runs:
  using: 'node16'
  main: 'dist/index.js'