name: test-of-action

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: create release
        id: release
        uses: ./
        with:
          sha: ${{ github.sha }}
          tag: v1
          append-tag: PROD
          gh-token: ${{ env.GH_TOKEN }}