name: test-of-action

on: 
  workflow_dispatch:
    inputs:
      name:
        type: choice
        required: true
        default: 'prod'
        description: Deploy
        options: 
        - prod
        - hml
      tag:
        description: Version
        required: true
        type: string
permissions: write-all

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: create release
        id: release
        uses: ./
        with:
          branch: ${{ github.ref_name }}
          tag: ${{inputs.tag}}
          append-tag: ${{inputs.name}}
          gh-token: ${{ env.GH_TOKEN }}