name: test-of-action

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: verify if rebased
        id: verify
        uses: ./
        with:
          sha: ${{ github.sha }}
          tag: v1
          gh-token: ${{ env.GH_TOKEN }}